Document envelope types
cloudfoundry/docs-loggregator pull request #78
Opened 2023-09-11 22:50 UTC by rroberts2222

This documentation of envelope types exists already in the [loggregator-api README](https://github.com/cloudfoundry/loggregator-api#v2-envelope-types). Adding it to the main documentation to make it easier to find and clear up any confusion.

2023-09-11 23:54 UTC, chombium requested changes
@rroberts2222 I know that your intentions are good, but why haven't you simply linked the [README.md](https://github.com/cloudfoundry/loggregator-api/blob/master/README.md) from the Loggregator API repo. This and the other PRs that you've opened simply raise the maintenance effort, because we would have to maintain the docs multiple times ;)

2023-09-13 18:20 UTC, bobbygeeze reviewed
Need an opening paragraph to introduce the topic. Please provide.  Also, do not use "e.g" use fox example instead.

2023-09-15 22:45 UTC, rroberts2222 commented
It is updated as link to the README and moved to the section about loggregator instead of a very small section on its own. Let me know what you think @chombium and @bobbygeeze! Once this PR is straightened out, I will make changes to the other ones.

2023-09-22 17:28 UTC, rroberts2222 commented
closing PR since a similar change was made in commit https://github.com/cloudfoundry/docs-loggregator/commit/2e2bd8caf9629e1631bcef4d06d64957dc4ca9b4

2023-09-22 17:28 UTC, closed without merging