fix(container-metrics): Document `cpu_entitlement`
cloudfoundry/docs-loggregator pull request #88
Opened 2024-03-14 14:11 UTC by silvestre

https://github.com/cloudfoundry/cf-deployment/pull/1164 added the new
`cpu_entitlement` container metric and deprecated and removed by default
the old `absolute_entitlement` and `absolute_usage` metrics.

This PR documents the new container metric.

2024-03-14 14:24 UTC, silvestre commented
@acrmp @mkocher: As you contributed this change to diego, could you please check if my understanding and the proposed documentation is correct?

2024-03-14 14:52 UTC, chombium requested changes
Hi @silvestre,

thank you very much for your contribution. 

Your change is s a step in the right direction. You've changed everything to be aligned with the new defaults set in the cf-deployment.

IMO. The new `cpu_entitlement` should be added to the list and there should be a paragraph saying that there is a `rep` job property called [app_metric_exclusion_filter](https://github.com/cloudfoundry/diego-release/blob/develop/jobs/rep/spec#L82C1-L85C22) for filtering out (excluding) some of the container metrics. The old `absolute_entitlement`, `absolute_usage` should be left inside the list. 

You can also mention that by default in diego rep the `cpu_entitlement` is excluded. The cf-deployment filters the `absolute_entitlement`, `absolute_usage` metrics and lets `cpu_entitlement` metric to be emitted.

@mkocher, @acrmp wdyt?

Best Regards,
Jovan

2024-03-14 17:01 UTC, ctlong approved these changes
LGTM

2024-03-14 17:30 UTC, acrmp commented
Thanks @silvestre. Looks good, as Jovan said it would be nice to retain the old `absolute_entitlement` and `absolute_usage` metrics in the list and add a note that the set of metrics available may vary depending on the configuration.

It looks like we could also change `CpuPercentage` to `cpu` while we are here.

Thanks!

2024-03-15 12:13 UTC, chombium approved these changes
Hi @silvestre,

thank you very much for the prompt reply and the changes made. 

LGTM!

2024-03-15 12:34 UTC, silvestre commented
@anita-flegg Would you be able to merge this? It seems you are the only one merging PRs in this repo. :smile:

2024-03-15 13:17 UTC, anita-flegg commented
Thanks, everyone! Great to see your commitment to making the docs better :)

2024-03-15 13:17 UTC, merged