update information about container networking metrics
cloudfoundry/docs-loggregator pull request #97
Opened 2024-12-09 20:37 UTC by ameowlia

* this feature is only available in OS currently

Questions for @pspinrad: 
* I used the term "TPCF" in this PR. Is that the correct way to refer to the TAS tile? 
* Can you please update this for all supported versions of this doc?

2024-12-12 14:18 UTC, anita-flegg requested changes

2024-12-12 16:38 UTC, ameowlia commented on container-metrics.html.md.erb
> +      This metric is not available in TPCF yet.
Thank you for these suggestions @anita-flegg! I will update this.

2024-12-12 18:10 UTC, ameowlia commented on container-metrics.html.md.erb
> +      This metric is not available in TPCF yet.
```suggestion
      This metric is not available in Tanzu Platform for Cloud Foundry.
```

2024-12-12 18:13 UTC, ameowlia commented on container-metrics.html.md.erb
> +      This metric is not available in TPCF yet.
Fixed both cases!

2024-12-12 18:14 UTC, ameowlia commented
@anita-flegg - I have made the changes you suggested. Thank you for your help!

2024-12-13 13:34 UTC, merged

2024-12-13 13:38 UTC, anita-flegg commented
Thanks, @ameowlia !
@pspinrad to cherry-pick to all the places this should go -- I assume TAS-6.0, TAS-5.0, TAS-4.0, and the new 10.0 branch...?

2024-12-13 16:04 UTC, ameowlia commented
Yes! All of those places are correct!